model:
  seed: 42
  encoder_dim: 1024
  num_experts: 24
  select_k: 5
  top_k: 2
  expert_dim: 128
  num_classes: 2

train:
  model_name: "DSD_ASV019"
  layer_select_model_name: "LS_ASV019"
  nb_samp: 64600
  weight_decay: 0.0001
  batch_size: 128
  lr: 0.0001
  num_epochs: 20
  nb_worker: 8
  patience: 5
  warmup_epochs: 3
  enable_contrastive_epoch: 99
  consistency_warmup: 5
  aug_prob: 0.5
  aug_method: "additive_noise"
  unknown_cluster_interval: 5
  router_temperature: 2.0
  k_bonafide: 5
  k_spoof: 10
  momentum: 0.1
  prototype_temperature: 0.1
  sample_to_temperature: 0.07
  datasets: ["Asvspoof2019_LA"]
  adaptive_length_scale: 1.5
  adaptive_length_weight: 1.0
  router_temp_start: 2.5
  router_temp_end: 2.0
  router_temp_anneal_epochs: 10
  subsample_val_epoch: 3


inference:
  task: "in_the_wild"
  upload_plots: true

loss:
  lambda_ce: 1.0
  lambda_contrastive: 0.0
  lambda_limp: 0.3
  lambda_load: 1.0
  lambda_entropy: 0.1
  lambda_router_supervised: 0.1
  lambda_length: 0.0

paths:
  aasist_config_path: "./config/AASIST.conf"
  save_path: "./checkpoints"
  model_folder: "./checkpoints"
  log_path: "./logs"
  plot_path: "./plot"
  wav2vec_path: "./pretrained_models/wav2vec2-xls-r-300m"
  onnx_path: "./onnx_models/xlsr_base_fp16.onnx"

meta:
  description: "Layer-Selection + DSD"
  discord_webhook: "https://discord.com/api/webhooks/1363816820028739756/_k6XM40W5f4OaRN0RJqWweG-AP-8rQbLIcZ_7x4YzK0ZjqPus7fSV9L_ul19B2pwrP9D"
  secret_yml_path: "./config/secret.yml"
  project_name: "audio-deepfake-detection"